#!/bin/bash
# batch_git_push
#   This script runs git push in all sub-directories for all the repositories in https://github.com/aimldl.
#
#   Rev.8: 2020-06-19 (Fri)
#   Rev.7: 2020-05-28 (Thu)
#   Rev.6: 2020-03-01 (Sun)
#   Rev.5: 2020-02-25 (Tue)
#   Rev.4: 2020-02-06 (Thu) 
#   Rev.3: 2020-02-06 (Thu) 
#   Rev.2: 2019-11-19 (Tue)
#   Rev.1: 2019-11-15 (Fri)
#   Draft: 2019-11-11 (Mon)
#
# Syntax
#   $ ./batch_git_push
#     adds the default message specified in MSG.
#   $ ./batch_git_push "Pass this message to git commit -m"
#     saves the input argument to MSG. Don't forget to use parenthesis.
#
# Doing it manually
#   Assuming you will push everything in directory "computing_environments".
#   $ cd aimldl/
#   $ cd computing_environments/
#   $ git add .
#   $ git commit -m "Add a new file"
#   $ git push
#   $ cd ..

dir_root=${PWD}
repos="documents technical_skills aimldl.github.io non_technical_skills private"
#repos="ml_dl aimldl.github.io python3 documents aws computing_environments"
#repos="sql matlab cpp bindsnet career private"

MSG=${1:-"Add new stuff by batch_git_push"}
for repo in ${repos};
do
  CMD="cd ${dir_root}/${repo}"
  echo $CMD
  eval $CMD

  CMD="git add . && git commit -m '${MSG}' && git push"
  echo $CMD
  eval $CMD
done
