#!/bin/bash
# mrun_sgf2gsp     is a wrapper around sgf2gsp.
#                  mrun_sgf2gsp runs sgf2gsp multiple times.
#
# Last updated:  Oct.15, 2008 (Wed)
# First written: Oct.15, 2008 (Wed)
# Version: 1.1
# Written by Tae-Hyung D. Kim, tk424@mst.edu

cd ../sgf_files/9x9_games
for filename in `ls`;do
   COMMAND="../../bin/sgf2gsp ${filename}";
   eval ${COMMAND}
done
