#!/bin/bash
OPTION_FORMAT='mp3'
OPTION_VOICE='Joey'
OPTIONS="--output-format ${OPTION_FORMAT} --voice-id ${OPTION_VOICE}"

TEXT="Slide 30 for 2 min. Finally, the AWS DeepRacer League will officially kick off later in 2019 with an online experience for everyone, and physical events at select locations co-hosted with AWS Summits. Stay tuned! Developers train their models via the console for the fastest lap time, and can submit lap times to online leaderboards, or compete in-person at AWS Summits. Winners of each stage progress to the DRL Cup at reinvent 2019, to win the Champions Cup. Slide 31. Thank you and Q&A for 9 mins."
FILE_NAME="rl4bona-13.mp3"
CMD="aws polly synthesize-speech ${OPTIONS} --text '${TEXT}' ${FILE_NAME}"
echo $CMD
eval $CMD
