#!/bin/bash
#  install_ubuntu_productivity_packages
#    Run this script after installing Ubuntu Linux and install the productivity packages
#    For Ubuntu 18.04 LTS
#
#  * Rev.6: 2020-07-23 (Thu)
#  * Rev.5: 2020-07-21 (Tue)
#  * Rev.4: 2020-07-16 (Thu)
#  * Rev.3: 2020-07-14 (Tue)
#  * Rev.2: 2020-06-27 (Mon)
#  * Rev.1: 2020-06-22 (Mon)
#  * Draft: 2018-09-10 (Mon)
#
#  Usage:
#    To run this script, 
#      $ chmod +x install_ubuntu_productivity_packages 
#      $ ./install_ubuntu_basic_packages 
#      [sudo] password for k8smaster:
#
#    To edit this file, use a text editor.
#      $ nano install_ubuntu_productivity_packages
#    nano is my choice of text editor, but you may use other text editor such as vi, vim, or emacs.

#----------------------------------------------------
# The following commands are used for

# Install the Linux Kernel Header
#sudo apt-get install linux-headers-$(uname -r)
# Is this necessary when Ubuntu is updated and upgraded?

#sudo apt install -y zip
#sudo apt install -y unzip
#sudo apt-get install -y software-properties-common
#sudo apt install -y nano
#sudo apt install -y wget
#sudo apt install -y iproute2
#sudo apt install -y strace
#sudo apt install -y diffstat
#sudo apt install -y tcpdump
# Installing vim overwrites gedit. I don't like it.
#sudo apt install -y vim

# git
sudo apt install -y git

# meld
sudo apt-get update -y
sudo apt-get install -y meld

# typora
wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
sudo add-apt-repository 'deb https://typora.io/linux ./'
sudo apt-get update
sudo apt-get install -y typora

# gimp
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp
sudo apt-get update
sudo apt-get install -y gimp

# audacity
#sudo add-apt-repository ppa:ubuntuhandbook1/audacity
#sudo apt-get update
sudo apt-get install -y audacity

# Nomacs
#   https://blog.naver.com/aimldl/221595457917
#   https://launchpad.net/~nomacs/+archive/ubuntu/stable
sudo add-apt-repository -y ppa:nomacs/stable
sudo apt update
sudo apt install -y nomacs

# Google Chrome
#   https://github.com/aimldl/technical_skills/blob/master/computing_environments/linux_ubuntu/how_to_install/google-chrome.md
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install -y ./google-chrome-stable_current_amd64.deb

# Korean Language Packs
#sudo apt install -y language-pack-ko
#sudo apt install -y korean*
