#!/bin/bash
#  install_ubuntu_basic_packages
#    Run this script after installing Ubuntu Linux and install the basic packages
#    For Ubuntu 18.04 LTS
#
#  * Rev.3: 2020-07-14 (Tue)
#  * Rev.2: 2020-06-27 (Mon)
#  * Rev.1: 2020-06-22 (Mon)
#  * Draft: 2018-09-10 (Mon)
#
#  Usage:
#    To run this script, 
#      $ chmod +x install_ubuntu_basic_packages 
#      $ ./install_ubuntu_basic_packages 
#
#    To edit this file, use a text editor.
#      $ nano install_ubuntu_basic_packages
#    nano is my choice of text editor, but you may use other text editor such as vi, vim, or emacs.

sudo apt update && sudo apt-get upgrade -y

# Install Dependencies
sudo apt install -y build-essential
sudo apt install -y cmake
sudo apt install -y git
sudo apt-get install -y python-dev python3-dev python-pip python3-pip

# Install some convenient packages
sudo apt install -y tree
sudo apt install -y vim
sudo apt install -y curl
sudo apt install -y screen
sudo apt install -y net-tools
sudo apt install -y pkg-config

# Google Chrome
#   https://github.com/aimldl/technical_skills/blob/master/computing_environments/linux_ubuntu/how_to_install/google-chrome.md
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install -y ./google-chrome-stable_current_amd64.deb

# gnome-tweak-tool
sudo add-apt-repository universe
sudo apt install -y gnome-tweak-tool

#----------------------------------------------------
# The following commands are used for

# Install the Linux Kernel Header
#sudo apt-get install linux-headers-$(uname -r)
# Is this necessary when Ubuntu is updated and upgraded?

#sudo apt install -y zip
#sudo apt install -y unzip
#sudo apt-get install -y software-properties-common
#sudo apt install -y nano
#sudo apt install -y wget
#sudo apt install -y iproute2
#sudo apt install -y strace
#sudo apt install -y diffstat
#sudo apt install -y tcpdump


