# Dockerfile
#
#  The objective of this Dockerfile is to build an image for NVIDIA DGX-1 supercomputer.
#  
#  Last updated: 2018-05-25 (Fri)
#  First written: 2018-05-25 (Fri)
#  Writtey by Tae-Hyung "T" Kim, Ph.D.

FROM nvidia/cuda:9.0-base-ubuntu16.04

LABEL maintainer="Tae-Hyung T Kim, Ph.D."
