#!/bin/bash
# batch_git_pull
#   This script runs git pull in all sub-directories for all the repositories in https://github.com/aimldl.
#
# * Rev.15: 2020-11-05 (Thu)
# * Rev.14: 2020-10-14 (Wed)
# * Rev.13: 2020-10-03 (Sat)
# * Rev.12: 2020-09-06 (Sun)
# * Rev.11: 2020-08-23 (Sun)
# * Rev.10: 2020-07-28 (Tue)
# * Rev.9: 2020-07-14 (Tue)
# * Rev.8: 2020-06-19 (Fri)
# * Rev.7: 2020-05-28 (Thu)
# * Rev.6: 2020-03-01 (Sun)
# * Rev.5: 2020-02-25 (Tue)
# * Rev.4: 2020-02-06 (Thu) 
# * Rev.3: 2020-02-06 (Thu) 
# * Rev.2: 2019-11-19 (Tue)
# * Rev.1: 2019-11-15 (Fri)
# * Draft: 2019-11-11 (Mon)
#
# Usage
#   $ chmod +x batch_git_pull
#   $ ./batch_git_pull
#
# TODO: this script should work, but has not been tested upon Rev.9.

run() {
  COMMAND=$1
  echo $COMMAND
  eval $COMMAND
}

dir_root=${PWD}
repos="aimldl.github.io coding environments pytorch tensorflow topics_in projects"
for repo in ${repos}; do
  run "cd ${dir_root}/${repo}"  # cd to the repo's directory
  run "git pull"                # pull from the specified repo
done

# EOF
