#!/bin/bash
# batch_git_pull
#   This script runs git pull in all sub-directories for all the repositories in https://github.com/aimldl.
#
# * Rev.3: 2020-11-14 (Sat)
# * Rev.2: 2020-10-03 (Sat)
# * Draft: 2019-11-11 (Mon)
#
# Usage
#   $ chmod +x batch_git_pull
#   $ ./batch_git_pull

run() {
  COMMAND=$1
  echo $COMMAND
  eval $COMMAND
}

dir_root=${PWD}
repos="aimldl.github.io coding environments pytorch tensorflow topics_in projects"
for repo in ${repos}; do
  run "cd ${dir_root}/${repo}"  # cd to the repo's directory
  run "git pull"                # pull from the specified repo
done

# EOF
