#!/bin/bash
# batch_git_push
#   This script runs git push in all sub-directories for all the repositories in https://github.com/aimldl.
#
# * Rev.3: 2020-11-14 (Sat)
# * Rev.2: 2020-10-03 (Sat)
# * Draft: 2019-11-11 (Mon)
#
# Syntax
#   $ ./batch_git_push
#     adds the default message specified in MSG.
#   $ ./batch_git_push "Pass this message to git commit -m"
#     saves the input argument to MSG. Don't forget to use parenthesis.
#
# Doing it manually
#   Assuming you will push everything in directory "computing_environments".
#   $ cd aimldl/
#   $ cd computing_environments/
#   $ git add .
#   $ git commit -m "Add a new file"
#   $ git push
#   $ cd ..
#
# TODO: this script should work, but has not been tested upon Rev.10

run() {
  COMMAND=$1
  echo $COMMAND
  eval $COMMAND
}

dir_root=${PWD}
MSG=${1:-"Add new stuff by batch_git_push"}
repos="aimldl.github.io coding environments pytorch tensorflow topics_in projects"
for repo in ${repos}; do
  run "cd ${dir_root}/${repo}"
  run "git add . && git commit -m '${MSG}' && git push"
done

# EOF
