#!/bin/bash
# batch_git_clone
#   This script git-clones all the repositories in https://github.com/aimldl
#   A private repository requires authentication.
#
# * Rev.12: 2020-10-03 (Sat)
# * Rev.11: 2020-09-06 (Sun)
# * Rev.10: 2020-08-23 (Sun)
# * Rev.9: 2020-07-28 (Tue)
# * Rev.8: 2020-07-14 (Tue)
# * Rev.7: 2020-06-19 (Fri)
# * Rev.6: 2020-03-01 (Sun)
# * Rev.5: 2020-02-25 (Tue)
# * Rev.4: 2020-02-06 (Thu) 
# * Rev.3: 2020-01-26 (Sun)
# * Rev.2: 2019-12-27 (Fri)
# * Rev.1: 2019-11-19 (Tue)
# * Draft: 2019-11-01 (Fri)
#
# Usage
#   $ chmod +x batch_git_clone
#   $ ./batch_git_clone

run() {
  COMMAND=$1
  echo $COMMAND
  eval $COMMAND
}

repos="aimldl.github.io topics_in non_technical_skills technical_skills kaggle tensorflow pytorch private"
for repo in ${repos}; do
  run "git clone https://github.com/aimldl/${repo}.git"
done

# EOF
