#!/bin/bash
# run
#
# Usage
#  $ sudo mysql -u root -p
#  [sudo] password for aimldl: 
#  Enter password: 
#  Welcome to the MySQL monitor.  Commands end with ; or \g.
#  Your MySQL connection id is 2
#  Server version: 5.7.30-0ubuntu0.18.04.1 (Ubuntu)
#  
#  Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.
#  
#  Oracle is a registered trademark of Oracle Corporation and/or its
#  affiliates. Other names may be trademarks of their respective
#  owners.
#  
#  Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
#  
#  mysql> exit
#  Bye
#  $

cmd="sudo mysql -u root -p"
echo $cmd
eval $cmd
