#!/bin/bash
# install_cuda_packages-part2
#   * Draft: 2021-01-25 (Mon)

# Define function(s)
run() {
  COMMAND=$1
  echo $COMMAND
  eval $COMMAND
}

#echo '--------------------------------------------------------------------'
#echo 'Setting up the NVIDIA GPU card(s) ...'
#echo '--------------------------------------------------------------------'

# Check if the installation file does not exist, download it
FILE="libnvinfer7_7.1.3-1+cuda11.0_amd64.deb"
FILE_DOWNLOAD_LINK="https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/$FILE"
if [ ! -f "$FILE" ]; then
    echo "$FILE does not exist. Downloading it ..."
    run "wget $FILE_DOWNLOAD_LINK"
else
    echo "$FILE does exist. Skip downloading it ..."
fi

run "sudo apt install -y ./$FILE"
run 'sudo apt-get update -y'

# Install development and runtime libraries (~4GB)
run 'sudo apt-get install -y --no-install-recommends \
         cuda-11-0 \
         libcudnn8=8.0.4.30-1+cuda11.0  \
         libcudnn8-dev=8.0.4.30-1+cuda11.0'

# Install TensorRT. Requires that libcudnn8 is installed above.
run 'sudo apt-get install -y --no-install-recommends libnvinfer7=7.1.3-1+cuda11.0 \
         libnvinfer-dev=7.1.3-1+cuda11.0 \
         libnvinfer-plugin7=7.1.3-1+cuda11.0'
