#!/bin/bash
# batch_git_pull
#   This script runs git pull in all sub-directories for all the repositories in https://github.com/aimldl.
#
#   Rev.2: 2019-12-27 (Fri)
#   Rev.1: 2019-11-19 (Tue)
#   Draft: 2019-11-11 (Mon)

dir_root=${PWD}
repos="aws cpp python3 sql computing_environments documents matlab bindsnet career private"
for repo in ${repos};
do
  #CMD="cd $repo && git pull && cd .."
  #echo $CMD
  #eval $CMD

  CMD="cd ${dir_root}/${repo}"
  echo $CMD
  eval $CMD

  CMD="git pull"
  echo $CMD
  eval $CMD
done

# The above lines are basically the same as below.
# cd aws && git pull && cd ..
# cd cpp && git pull && cd ..
# cd python3 && git pull && cd ..
# cd sql && git pull && cd .. 
# cd computing_environments && git pull && cd ..
# cd matlab && git pull && cd .. 
# cd private && git pull && cd .. 
# cd bindsnet && git pull && cd ..
