#!/bin/bash
# count_files_in_subdirs
DIRS=`ls -d */`
for dir in ${DIRS};
do
  cmd="cd $dir"
  echo $cmd
  eval $cmd

  cmd="ls | wc -l"
  echo $cmd
  eval $cmd

  cmd="cd ..."
  echo $cmd
  eval $cmd
done

# TODO: Fix a bug
(hula) aimldl@GPU-Desktop:~/aimldl/topics-medium/Building a Dead Simple Speech Recognition Engine using ConvNet in Keras/data/input$ ./count_files_in_subdirs
cd _background_noise_/
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd bed/
./count_files_in_subdirs: line 8: cd: bed/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd bird/
./count_files_in_subdirs: line 8: cd: bird/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd cat/
./count_files_in_subdirs: line 8: cd: cat/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd dog/
./count_files_in_subdirs: line 8: cd: dog/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd down/
./count_files_in_subdirs: line 8: cd: down/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd eight/
./count_files_in_subdirs: line 8: cd: eight/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd five/
./count_files_in_subdirs: line 8: cd: five/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd four/
./count_files_in_subdirs: line 8: cd: four/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd go/
./count_files_in_subdirs: line 8: cd: go/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd happy/
./count_files_in_subdirs: line 8: cd: happy/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd house/
./count_files_in_subdirs: line 8: cd: house/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd left/
./count_files_in_subdirs: line 8: cd: left/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd marvin/
./count_files_in_subdirs: line 8: cd: marvin/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd nine/
./count_files_in_subdirs: line 8: cd: nine/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd no/
./count_files_in_subdirs: line 8: cd: no/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd off/
./count_files_in_subdirs: line 8: cd: off/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd on/
./count_files_in_subdirs: line 8: cd: on/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd one/
./count_files_in_subdirs: line 8: cd: one/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd right/
./count_files_in_subdirs: line 8: cd: right/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd seven/
./count_files_in_subdirs: line 8: cd: seven/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd sheila/
./count_files_in_subdirs: line 8: cd: sheila/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd six/
./count_files_in_subdirs: line 8: cd: six/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd stop/
./count_files_in_subdirs: line 8: cd: stop/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd three/
./count_files_in_subdirs: line 8: cd: three/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd tree/
./count_files_in_subdirs: line 8: cd: tree/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd two/
./count_files_in_subdirs: line 8: cd: two/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd up/
./count_files_in_subdirs: line 8: cd: up/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd wow/
./count_files_in_subdirs: line 8: cd: wow/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd yes/
./count_files_in_subdirs: line 8: cd: yes/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
cd zero/
./count_files_in_subdirs: line 8: cd: zero/: No such file or directory
ls | wc -l
7
cd ...
./count_files_in_subdirs: line 16: cd: ...: No such file or directory
