#!/bin/bash
#  run_secrets
#   * Draft: 2020-08-12 (Wed)

run() {
  COMMAND=$1
  echo "$COMMAND ..."
  eval $COMMAND
}

run 'kubectl create -f test_secrets.yaml'
# secret/apikey created

run 'kubectl get secrets'
# NAME                  TYPE                                  DATA   AGE
# apikey                Opaque                                2      51s
# default-token-r6xj6   kubernetes.io/service-account-token   3      24h

run 'kubectl describe secrets'
# Name:         apikey
# Namespace:    default
# Labels:       <none>
# Annotations:  <none>
#
# Type:  Opaque
#
# Data
# ====
# id:   3 bytes
# key:  7 bytes
#
#
# Name:         default-token-r6xj6
# Namespace:    default
# Labels:       <none>
# Annotations:  kubernetes.io/service-account.name: default
#               kubernetes.io/service-account.uid: 6f994781-5f6d-4215-ac7b-f34e5457e831
#
# Type:  kubernetes.io/service-account-token
#
# Data
# ====
# ca.crt:     1025 bytes
# namespace:  7 bytes
# token:      eyJhbGciOiJSUzI1NiIsImtpZCI6ImhCWFpYUzAzQ1pfdFRnbFhQMjIyTVlOb0Rla3pvQldfc2twOXJZNkhDdmcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tcjZ4ajYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjZmOTk0NzgxLTVmNmQtNDIxNS1hYzdiLWYzNGU1NDU3ZTgzMSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.U-K0StYEUh5jkeVc1WAXwD1cMnLJItD0Tbnyg8Vy8z104Rpg03rWqKxLgTanYUbIeRoVjJGgVQdiWxF1Q26wNFstyuNs_RYDwA9bgKOPbqLgzLDXyus0aT-lc5alulzl9xq6GKkPAsu9I0zOGUB-RszlH8B9oZgIuCBLEP1vW8XEEjVvv_Emf2oUmGiXhFxKEQiCnKng_kiypS2QNB8mCt1S3v5tVVjrR2qPklsSpxd8zfay-cyb6f3g3F8NgPddqtu9dM3QhVxygJdhYD7k4ihl0O4l849hcXtI79FoyITrKO5Cw9OQjQaTrsDKeI-0nuY824TN1xZUfw7zz4p5CA

