#!/bin/bash
# batch_git_clone
#   This script git-clones all the repositories in https://github.com/aimldl
#   Note "private" is a private repository which requires authentication.
#
#   Rev.2: 2019-12-27 (Fri)
#   Rev.1: 2019-11-19 (Tue)
#   Draft: 2019-11-01 (Fri)
#
# git clone https://github.com/aimldl/aws.git
# git clone https://github.com/aimldl/cpp.git
# git clone https://github.com/aimldl/python3.git
# git clone https://github.com/aimldl/sql.git
# git clone https://github.com/aimldl/computing_environments.git
# git clone https://github.com/aimldl/matlab.git
# git clone https://github.com/aimldl/bindsnet.git
# git clone https://github.com/aimldl/private.git
#
# TODO: Run & see if the following for loop works properly. The above lines work fine.

repos="aws cpp python3 sql computing_environments documents matlab bindsnet career private"
for repo in ${repos};
do
  CMD="git clone https://github.com/aimldl/${repo}.git"
  echo $CMD
  eval $CMD
done
