#!/bin/bash
#  run_jupyter_notebook
#    * Draft: 2020-0324 (Tue)
#    runs jupyter notebook inside a Docker container.
#
#    The Docker container should be started with the "-p 8080:8080" option.
#      $ docker run -it -p 8080:8080 ...
#    For example,
#      $ docker run -it -p 8080:8080 --name conda aimldl/baseimage_python3.7.6_conda_4.8.2_ubuntu18.04.4 bash
#
#    Open and edit the .bashrc file.
#      (base) user@df4703dbba5f:~/bin$ cd      
#      (base) user@df4703dbba5f:~$ nano .bashrc
#    Add the following lines in .bashrc.
#     alias j="run_jupyter_notebook"
#     export PATH="/home/user/bin:$PATH"
#    Restart th Bash shell.
#      (base) user@df4703dbba5f:~$ bash
#      (base) user@df4703dbba5f:~$ 
#    Now a Jupyter Notebook can be launched simply by typing in:
#      (base) user@df4703dbba5f:~$ j
#    Anywhere because /home/use/bin is added to the PATH.

jupyter notebook --ip=0.0.0.0 --port=8080
