#!/bin/bash
# request_polly_all_voices-jp
#   requests Amazon Polly to read a text out loud by all voices (Japanese).
#
# * Rev.2: 2019-12-16 (Mon)
# * Rev.1: 2019-11-28 (Thu)
# * Draft: 2018-12-18 (Tue)
# Written by Tae-Hyung "T" Kim, Ph.D.
#
# Usage:
#   $ ./request_polly_simple "Input a text to read out loud"  output_filename.mp3
#     or to specify the format to pcm
#   $ ./request_polly_simple "Input a text to read out loud"  output_filename.pcm pcm

# Command line arguments

TEXT1="「ではみなさんは、そういうふうに川だと言われたり、乳の流れたあとだと言われたりしていた、このぼんやりと白いものがほんとうは何かご承知ですか」先生は、黒板につるした大きな黒い星座の図の、"

TEXT=${1:-"銀河鉄道の夜。宮沢賢治。${TEXT1}"}

FILE_NAME=${2:-"output_filename-jp.mp3"}
FORMAT=${3:-"mp3"}

BASE_NAME=$(basename ${FILE_NAME/.mp3})
#echo $BASE_NAME

# All voices for Japanese in the order of:
# Japanese (ja-JP)
# Source: https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
VOICES="Mizuki Takumi"
for VOICE in ${VOICES}; do
  NEW_FILE_NAME=${BASE_NAME}-${VOICE}.${FORMAT}

  OPTIONS="--output-format ${FORMAT} --voice-id ${VOICE}"
  CMD="aws polly synthesize-speech ${OPTIONS} --text '${TEXT}' ${NEW_FILE_NAME}"
  echo $CMD
  eval $CMD
done
