#!/bin/bash

for filename in *.aif; do
   cat $filename | awk '{ if ( $1>0 && $2>0 ) print $0;}' > tmp.aif
#   cat $filename | awk '{ if ( $1>0 && $2>0 ) printf("%d\t%d\n",$1,$2);}' > tmp.aif
   mv tmp.aif $filename;
done
