#!/bin/bash
# request_polly-how_are_you
# * Rev.1: 2019-11-28 (Thu)
# * Draft: 2018-12-18 (Tue)
# Written by Tae-Hyung "T" Kim, Ph.D.

# Examples
#   $ request_polly-how_are_you
#   aws polly synthesize-speech --output-format mp3 --voice-id Joey --text 'How are you?' how_are_you.mp3
#   /home/user_id/.local/lib/python2.7/site-packages/urllib3/util/ssl_.py:354: SNIMissingWarning: An HTTPS request has been made, ...
#   {
#       "ContentType": "audio/mpeg",
#       "RequestCharacters": "12"
#   }
#   $ ls
#   how_are_you.mp3
#   $

OPTION_FORMAT='mp3'
OPTION_VOICE='Joey'
OPTIONS="--output-format ${OPTION_FORMAT} --voice-id ${OPTION_VOICE}"
TEXT='How are you?'
FILE_NAME='how_are_you.mp3'

CMD="aws polly synthesize-speech ${OPTIONS} --text '${TEXT}' ${FILE_NAME}"
echo $CMD
eval $CMD
