#!/bin/bash
# run
# First written: 2019-01-28 (Mon)

echo "Updating keywords2remove.txt..."
sort config/keywords2remove.txt | uniq > config/a.txt
mv config/a.txt config/keywords2remove.txt

echo "Replacing the old filtered_sentences.txt to the new one..."
cp output/filtered_sentences.txt input/filtered_sentences.txt

cd Debug
./remove_sentences_effectively.exe
cd ..

