#!/bin/bash
# 
# Last updated:  Aug. 5, 2009 (Wed)
# First written: Aug. 5, 2009 (Wed)

# Go to the directory where nns is located.
echo "  cd ..;"
cd ..;

RUN_CMD="./nns -m mv:sr:na -a";
echo "  ${RUN_CMD}";
${RUN_CMD}

exit 0;
#EOF
