#!/bin/bash
#   run_flask
#
#   Last updated: 2018-06-14 (Thu)
#   First written: 2018-06-13 (Wed)
#
#   Written by Tae-Hyung "T" Kim, Ph.D
#
# The following command will run the image in the Bash terminal.
# 
# $ docker images
# REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
# flask-template            latest              088664a9e440        19 hours ago        951MB
# mrtonnet/flask-template   latest              088664a9e440        19 hours ago        951MB
# ...
# $ docker run -it 088664a9e440 /bin/bash
# root@da3d9e9bb08d:/#
#
# This script does it automatically.
# $ chmod +x run_flask
# $ ./run_flask
# root@f4bd14941471:/# exit
# exit
# $

################################
#  Define variables
################################
OPTION=$1
REPOSITORY="mrtonnet\/flask-quickstart"
TAG="version1.2"
#IMAGE_ID=`docker images | grep "mrtonnet\/flask-quickstart.*version1.2" | awk '{ print $3;}'`
IMAGE_ID=`docker images | grep "$REPOSITORY.*$TAG" | awk '{ print $3;}'`

################################
#  Decide what command to run  #
################################
if [ $# -eq 0 ]; then 
  CMD="docker run -it -p 5000:5000 $IMAGE_ID /bin/bash"
else
  if [ $OPTION = "bash" ]; then
    CMD="docker run -it -p 5000:5000 $IMAGE_ID /bin/bash"
  elif [ $OPTION = "detach" ]; then
    CMD="docker run -d -p 5000:5000 $IMAGE_ID "to-do""
  else
    echo "Error: OPTION $OPTION is not defined."
  fi
fi

################################
#       Run the command        #
################################
echo $CMD
eval $CMD

# Trouble shooting
#   I had an error to run this script. 
#     $ ./run_flask
#     docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"8cbd7940bd30\": executable file not found in $PATH": unknown.
#  The reason is because the IMAGE_ID is incorrect.
#  Last time, I commited the working container to another version, but I called one of the older containers.
#  For example, I have to run the latest version of version1.2 (IMAGE ID is cf0c53bb0810).
#    $ docker images
#    REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
#    <none>                       <none>              cab5a5dea009        29 hours ago        308MB
#    mrtonnet/flask-quickstart    version1.2          cf0c53bb0810        47 hours ago        951MB
#    mrtonnet/flask-quickstart    version1.1          8cbd7940bd30        3 days ago          951MB
#    mrtonnet/flask-socketio      version0.1          adb8be8a1ed6        3 days ago          951MB
#    mrtonnet/flask-quickstart    version1            f78f1f3bc206        3 days ago          951MB
#    mrtonnet/flask-quickstart    latest              53d2db6dbc94        4 days ago          951MB
#
#  So changing the value in TAG will fix the problem.
