#!/bin/bash
##### Rev.1: 2021-02-18 (Thu)
##### Draft: 2019-11-28 (Thu)

# ssh-aws_ec2_seoul-aimldl-office-2021

## Configuration
KEY='aimldl-office-2021.pem'
OPTION='-L 8888:localhost:8888 -X'
#OPTION='-L 8888:localhost:8888'
ID='ubuntu'
PUBLIC_IPV4_DNS="ec2-3-36-91-196.ap-northeast-2.compute.amazonaws.com"
PUBLIC_IPV4_ADDRESS='3.36.91.196'  # To make the IP address static, use Elastic IP.

## Function definition
run() {
  COMMAND=$1
  echo $COMMAND
  eval $COMMAND
}

## Main
run "ssh -i ${KEY} ${OPTION} ${ID}@${PUBLIC_IPV4_DNS}"
