#!/bin/bash
# request_polly-hello_world
# * Rev.1: 2019-11-28 (Thu)
# * Draft: 2018-12-18 (Tue)
# Written by Tae-Hyung "T" Kim, Ph.D.

OPTION_FORMAT='mp3'
OPTION_VOICE='Joanna'
OPTIONS="--output-format ${OPTION_FORMAT} --voice-id ${OPTION_VOICE}"
TEXT='Hello, world! This is T!'
FILE_NAME='hello_world.mp3'

CMD="aws polly synthesize-speech ${OPTIONS} --text '${TEXT}' ${FILE_NAME}"
echo $CMD
eval $CMD
